name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.3 # Add google_fonts here

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets folder to the Flutter project
  assets:
    - assets/icons/icon.jpg

flutter_icons: # Place flutter_icons at the top level
  android: true
  ios: true
  image_path: "assets/icons/icon.jpg"
