name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.3
  http: ^0.13.4  # Add http package here

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.jpg
    - assets/icons/img1.jpg
    - assets/icons/img2.jpg
    - assets/icons/img3.jpg
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/apple.png
    - assets/icons/login.png
    - assets/icons/signup.png
